language: node_js
node_js:
  - "8.12.0"
before_script:
  # We don't need to do lerna bootstrap, because it doesn't metter while using yarn workspaces
  - npm install -g codecov
  - yarn
  - yarn build
script:
  - yarn test
  - cd e2e
  - yarn
  - yarn serve &>/dev/null &
  - yarn wait-for-test-server
  - yarn start &>/dev/null &
  - yarn cypress:run
  - yarn build
  - cd ../
  - codecov
